SELECT * FROM customer 
LIMIT 10

--01. What is the total revenue generated by mal vs. femal customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender

--02. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE  discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)

--03. Which are the top 5 products with the highest average review rating?
SELECT item_purchased ,ROUND(AVG(review_rating::numeric),2) as "Average product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--04. Compare the average Purchase Amount between Standared and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

--05. Do subscribed customers spend more? Compare average spend and total revenue between subscribers
---and non-subscribers
SELECT subscription_status, 
COUNT(customer_id) as total_customer,
AVG(purchase_amount) as avg_spend,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY subscription_status 
ORDER BY avg_spend, total_revenue DESC;

--06 Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased , ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--07. Segment customers into New, Returning, and Loyal based on their total number of previous purchases 
--and show the count of each segment.
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS "No of customer"
FROM customer_type
GROUP BY customer_segment

--08. What are the top 3 most purchased products within each category?
with item_counts as (
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--10. What is the rvenue conntribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;